### ISSUE TITLE
api route 'pns/{kewenangan}/{year}' gives error

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/API#10]
When I try to visit `/api/pns/pah/2016` I get error that `2016_birms_prime.tbl_user` doesn't exist. 

@bdgcoder  can you share sample data in private dropbox? 

![screen shot 2017-09-18 at 2 52 11 pm](https://user-images.githubusercontent.com/521705/30558971-09f4f9ce-9c81-11e7-9320-0ed75cdf737a.png)

**Comment by bdgcoder** [comment]
I have been update 2016_birms_prime.sql and add 10 row data for table

**Comment by mireille-raad** [comment]
excellent!!! thank you very much
