### ISSUE TITLE
Google maps API free limits

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/API#11]
@bdgcoder Google maps API has the following limit per day for websites:
> Free up to 25,000 map loads per day.

https://developers.google.com/maps/pricing-and-plans/#details
![screen shot 2017-10-06 at 4 24 48 pm](https://user-images.githubusercontent.com/521705/31297145-eac021a6-aab2-11e7-93fb-c8287bef3815.png)

Is this ok?

**Comment by bdgcoder** [comment]
I think to start well enough.

**Comment by mireille-raad** [comment]
ok, great. closing the issue to mark as done
